import { describe, it, expect } from "vitest";
import { generateIndexJS, keyToFilePath } from "../governor/builder.js";

// ── 1. generateIndexJS ──────────────────────────────────────

describe("generateIndexJS", () => {
  it("generates valid entry point with all module types", () => {
    const metadata = {
      tools: ["kv_query", "web_fetch", "send_slack"],
      providers: ["llm", "llm_balance"],
      channels: ["slack"],
    };

    const code = generateIndexJS(metadata);

    // Imports
    expect(code).toContain("import { Brainstem } from './kernel.js'");
    expect(code).toContain("import { handleChat } from './hook-chat.js'");
    expect(code).toContain("import * as act from './act.js'");
    expect(code).toContain("import * as reflect from './reflect.js'");
    expect(code).toContain("import * as kv_query from './tools/kv_query.js'");
    expect(code).toContain("import * as web_fetch from './tools/web_fetch.js'");
    expect(code).toContain("import * as send_slack from './tools/send_slack.js'");
    expect(code).toContain("import * as llm from './providers/llm.js'");
    expect(code).toContain("import * as llm_balance from './providers/llm_balance.js'");
    expect(code).toContain("import * as slackAdapter from './channels/slack.js'");

    // Wiring
    expect(code).toContain("const TOOLS = {");
    expect(code).toContain("kv_query,");
    expect(code).toContain("'provider:llm': llm,");
    expect(code).toContain("'provider:llm_balance': llm_balance,");
    expect(code).toContain("slack: slackAdapter,");
    expect(code).toContain("const HOOKS = { act, reflect }");

    // Entry points
    expect(code).toContain("async scheduled(event, env, ctx)");
    expect(code).toContain("new Brainstem(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS })");
    expect(code).toContain("await brain.runScheduled()");
    expect(code).toContain("async fetch(request, env, ctx)");
    expect(code).toContain("handleChat(brain, channel, inbound, adapter)");
  });

  it("handles empty module lists", () => {
    const code = generateIndexJS({ tools: [], providers: [], channels: [] });

    expect(code).toContain("const TOOLS = {");
    expect(code).toContain("const PROVIDERS = {");
    expect(code).toContain("const CHANNELS = {");
    // Should still have kernel + hook imports
    expect(code).toContain("import { Brainstem } from './kernel.js'");
    expect(code).toContain("import * as act from './act.js'");
  });

  it("output is syntactically valid JS (no syntax errors)", () => {
    const metadata = {
      tools: ["kv_query", "computer"],
      providers: ["llm"],
      channels: ["slack"],
    };
    const code = generateIndexJS(metadata);

    // Should not throw when parsed as a module
    // (We can't fully parse ES modules in Node without import, but we can check for balanced braces)
    let depth = 0;
    for (const ch of code) {
      if (ch === '{') depth++;
      if (ch === '}') depth--;
    }
    expect(depth).toBe(0);
  });
});

// ── 2. keyToFilePath ─────────────────────────────────────────

describe("keyToFilePath", () => {
  it("maps tool code keys to tools/ paths", () => {
    expect(keyToFilePath("tool:kv_query:code")).toBe("tools/kv_query.js");
    expect(keyToFilePath("tool:send_slack:code")).toBe("tools/send_slack.js");
  });

  it("maps provider code keys to providers/ paths", () => {
    expect(keyToFilePath("provider:llm:code")).toBe("providers/llm.js");
    expect(keyToFilePath("provider:llm_balance:code")).toBe("providers/llm_balance.js");
  });

  it("maps channel code keys to channels/ paths", () => {
    expect(keyToFilePath("channel:slack:code")).toBe("channels/slack.js");
  });

  it("maps hook code keys to root paths", () => {
    expect(keyToFilePath("hook:act:code")).toBe("act.js");
    expect(keyToFilePath("hook:reflect:code")).toBe("reflect.js");
  });

  it("returns null for non-code keys", () => {
    expect(keyToFilePath("config:defaults")).toBeNull();
    expect(keyToFilePath("tool:kv_query:meta")).toBeNull();
    expect(keyToFilePath("prompt:orient")).toBeNull();
  });
});

// ── 3. Builder utility functions ─────────────────────────────

describe("builder utilities", () => {
  it("generateIndexJS includes auto-generated comment", () => {
    const code = generateIndexJS({ tools: [], providers: [], channels: [] });
    expect(code).toContain("Auto-generated by governor");
  });
});
