// Governor — Builder
// Reads code from KV and generates the index.js entry point for the runtime worker.
// Also collects all module files needed for the multipart upload.

// Sanitize a KV key into a valid JS identifier
function sanitizeVarName(raw) {
  const sanitized = raw.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(sanitized) ? sanitized : `_${sanitized}`;
}

function keyToVarName(key) {
  // tool:kv_query:code → kv_query, provider:llm:code → llm, channel:slack:code → slack
  const parts = key.split(':');
  const raw = parts[parts.length - 2] || parts[0];
  return sanitizeVarName(raw);
}

export function keyToFilePath(key) {
  if (key === 'kernel:source:kernel.js') return 'kernel.js';
  if (key === 'kernel:source:hook-communication.js') return 'hook-communication.js';
  if (key === 'kernel:source:authority-policy.js') return 'authority-policy.js';
  if (!key.endsWith(':code')) return null;
  if (key === 'hook:act:code') return 'act.js';
  if (key === 'hook:reflect:code') return 'reflect.js';
  if (key === 'hook:session:code') return 'userspace.js';
  if (key.startsWith('tool:')) return `tools/${keyToVarName(key)}.js`;
  if (key.startsWith('provider:')) return `providers/${keyToVarName(key)}.js`;
  if (key.startsWith('channel:')) return `channels/${keyToVarName(key)}.js`;
  return null;
}

export function filePathToKey(path) {
  if (!path || typeof path !== "string") return null;
  if (path === "kernel.js") return "kernel:source:kernel.js";
  if (path === "hook-communication.js") return "kernel:source:hook-communication.js";
  if (path === "authority-policy.js") return "kernel:source:authority-policy.js";
  if (path === "act.js") return "hook:act:code";
  if (path === "reflect.js") return "hook:reflect:code";
  if (path === "userspace.js") return "hook:session:code";
  if (path.startsWith("tools/") && path.endsWith(".js")) {
    return `tool:${path.slice("tools/".length, -".js".length)}:code`;
  }
  if (path.startsWith("providers/") && path.endsWith(".js")) {
    return `provider:${path.slice("providers/".length, -".js".length)}:code`;
  }
  if (path.startsWith("channels/") && path.endsWith(".js")) {
    return `channel:${path.slice("channels/".length, -".js".length)}:code`;
  }
  return null;
}

// Read all mutable code from KV and return { files, metadata }
export async function readCodeFromKV(kv) {
  const files = {};
  const metadata = { tools: [], providers: [], channels: [] };

  // Tools
  const toolKeys = await listKeysWithPrefix(kv, 'tool:');
  for (const key of toolKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`tools/${name}.js`] = code;
      metadata.tools.push(name);
    }
  }

  // Providers
  const providerKeys = await listKeysWithPrefix(kv, 'provider:');
  for (const key of providerKeys) {
    if (!key.endsWith(':code')) continue;
    // Skip last_working snapshots
    if (key.includes(':last_working:')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`providers/${name}.js`] = code;
      metadata.providers.push(name);
    }
  }

  // Channels
  const channelKeys = await listKeysWithPrefix(kv, 'channel:');
  for (const key of channelKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`channels/${name}.js`] = code;
      metadata.channels.push(name);
    }
  }

  // Policy hooks (act.js, reflect.js)
  const actCode = await kv.get('hook:act:code', 'text');
  if (actCode) files['act.js'] = actCode;

  const reflectCode = await kv.get('hook:reflect:code', 'text');
  if (reflectCode) files['reflect.js'] = reflectCode;

  const sessionCode = await kv.get('hook:session:code', 'text');
  if (sessionCode) files['userspace.js'] = sessionCode;

  // Immutable kernel source (kernel:* — agent cannot modify)
  const kernelCode = await kv.get('kernel:source:kernel.js', 'text');
  if (kernelCode) files['kernel.js'] = kernelCode;

  const commCode = await kv.get('kernel:source:hook-communication.js', 'text');
  if (commCode) files['hook-communication.js'] = commCode;

  const authorityPolicyCode = await kv.get('kernel:source:authority-policy.js', 'text');
  if (authorityPolicyCode) files['authority-policy.js'] = authorityPolicyCode;

  return { files, metadata };
}

// Generate the index.js entry point from module metadata
export function generateIndexJS(metadata) {
  const lines = [];

  lines.push("// Auto-generated by governor — do not edit manually");
  lines.push("import { Kernel } from './kernel.js';");
  lines.push("import { runTurn, ingestInbound, ingestInternal, handleCommand, createOutboxItem, checkOutbox } from './hook-communication.js';");
  lines.push("import { parseJobOutput } from './lib/parse-job-output.js';");
  lines.push("");

  // Policy hooks
  lines.push("import * as session from './userspace.js';");
  lines.push("import { classify as pulseClassify } from './userspace.js';");
  lines.push("");

  // Channel adapters
  for (const name of metadata.channels) {
    lines.push(`import * as ${sanitizeVarName(name)}Adapter from './channels/${name}.js';`);
  }
  lines.push("");

  // Tools
  for (const name of metadata.tools) {
    lines.push(`import * as ${sanitizeVarName(name)} from './tools/${name}.js';`);
  }
  lines.push("");

  // Providers
  for (const name of metadata.providers) {
    lines.push(`import * as ${sanitizeVarName(name)} from './providers/${name}.js';`);
  }
  lines.push("");

  // Wire modules
  lines.push("const TOOLS = {");
  for (const name of metadata.tools) {
    lines.push(`  ${sanitizeVarName(name)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const PROVIDERS = {");
  for (const name of metadata.providers) {
    lines.push(`  'provider:${name}': ${sanitizeVarName(name)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const CHANNELS = {");
  for (const name of metadata.channels) {
    lines.push(`  ${name}: ${sanitizeVarName(name)}Adapter,`);
  }
  lines.push("};");
  lines.push("");

  // EVENT_HANDLERS — immediate event handlers
  lines.push("const EVENT_HANDLERS = {");
  lines.push("  sessionTrigger: async (K, event) => {");
  lines.push('    try {');
  lines.push('      const schedule = await K.kvGet("session_schedule");');
  lines.push('      if (schedule?.next_session_after) {');
  lines.push('        const advanceTo = Date.now() + 30 * 1000;');
  lines.push('        if (new Date(schedule.next_session_after).getTime() > advanceTo) {');
  lines.push('          await K.kvWriteSafe("session_schedule", {');
  lines.push('            ...schedule,');
  lines.push('            next_session_after: new Date(advanceTo).toISOString(),');
  lines.push('          });');
  lines.push('        }');
  lines.push('      }');
  lines.push('    } catch (err) {');
  lines.push('      await K.karmaRecord({ event: "session_wake_error", error: err.message });');
  lines.push('    }');
  lines.push("  },");
  lines.push("};");
  lines.push("");

  lines.push("function decodeCallbackBase64(value) {");
  lines.push("  const normalized = String(value || '').replace(/\\s+/g, '');");
  lines.push("  if (!normalized) return null;");
  lines.push("  const binary = atob(normalized);");
  lines.push("  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));");
  lines.push("  return new TextDecoder().decode(bytes);");
  lines.push("}");
  lines.push("");

  lines.push("async function advanceSessionSchedule(env, defaults, advanceSeconds) {");
  lines.push("  const schedule = await env.KV.get('session_schedule', 'json');");
  lines.push("  const nextSessionAfter = new Date(Date.now() + advanceSeconds * 1000).toISOString();");
  lines.push("");
  lines.push("  if (!schedule) {");
  lines.push("    await env.KV.put('session_schedule', JSON.stringify({");
  lines.push("      next_session_after: nextSessionAfter,");
  lines.push("      interval_seconds: defaults?.schedule?.interval_seconds || 21600,");
  lines.push("      no_action_streak: 0,");
  lines.push("    }));");
  lines.push("    return;");
  lines.push("  }");
  lines.push("");
  lines.push("  if (!schedule.next_session_after || new Date(schedule.next_session_after).getTime() > Date.now() + advanceSeconds * 1000) {");
  lines.push("    await env.KV.put('session_schedule', JSON.stringify({");
  lines.push("      ...schedule,");
  lines.push("      next_session_after: nextSessionAfter,");
  lines.push("    }));");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // HOOKS — tick (userspace) + deferred processors (run inside lock after tick)
  lines.push("const HOOKS = {");
  lines.push("  tick: session,");
  lines.push("  deferred: {");
  lines.push("    comms: {");
  lines.push("      async run(K, events) {");
  lines.push("        const byConv = {};");
  lines.push("        for (const ev of events) {");
  lines.push('          let turn;');
  lines.push('          if (ev.type === "inbound_message") { turn = ev; if (!turn.idempotency_key) turn.idempotency_key = ev.key; }');
  lines.push('          else { turn = await ingestInternal(K, ev); }');
  lines.push('          if (!turn) {');
  lines.push('            if (ev.key) await K.deleteEvent(ev.key);');
  lines.push('            await K.karmaRecord({ event: "comms_unroutable", event_type: ev.type, event_key: ev.key });');
  lines.push('            continue;');
  lines.push('          }');
  lines.push('          const cid = turn.conversation_id;');
  lines.push('          if (!byConv[cid]) byConv[cid] = [];');
  lines.push('          byConv[cid].push(turn);');
  lines.push("        }");
  lines.push("        for (const [convId, turns] of Object.entries(byConv)) {");
  lines.push("          try {");
  lines.push("            const claimed = [];");
  lines.push("            for (const t of turns) {");
  lines.push("              if (t.idempotency_key) {");
  lines.push("                const ok = await K.claimEvent(t.idempotency_key, await K.getExecutionId());");
  lines.push("                if (ok) claimed.push(t);");
  lines.push("              } else { claimed.push(t); }");
  lines.push("            }");
  lines.push("            if (claimed.length === 0) continue;");
  lines.push("            const result = await runTurn(K, convId, claimed);");
  lines.push("            for (const t of claimed) {");
  lines.push("              if (!t.idempotency_key) continue;");
  lines.push('              if (result.action === "sent" || result.action === "discarded") {');
  lines.push("                await K.deleteEvent(t.idempotency_key);");
  lines.push('              } else if (result.action === "held") {');
  lines.push("                await createOutboxItem(K, convId, t.content, result.reason, result.release_after, [t.idempotency_key]);");
  lines.push("                await K.deleteEvent(t.idempotency_key);");
  lines.push("              } else {");
  lines.push("                await K.releaseEvent(t.idempotency_key);");
  lines.push("              }");
  lines.push("            }");
  lines.push("          } catch (err) {");
  lines.push('            await K.karmaRecord({ event: "comms_error", conversation: convId, error: err.message });');
  lines.push("            for (const t of turns) {");
  lines.push("              if (t.idempotency_key) {");
  lines.push("                try { await K.releaseEvent(t.idempotency_key); } catch {}");
  lines.push("              }");
  lines.push("            }");
  lines.push("          }");
  lines.push("        }");
  lines.push("        const dueItems = await checkOutbox(K);");
  lines.push("        for (const item of dueItems) {");
  lines.push("          try {");
  lines.push("            const turn = {");
  lines.push("              conversation_id: item.conversation_id,");
  lines.push("              reply_target: null,");
  lines.push('              source: "internal",');
  lines.push("              content: item.content,");
  lines.push('              intent: "share",');
  lines.push("              idempotency_key: item.key || null,");
  lines.push("              metadata: { outbox_id: item.id },");
  lines.push("            };");
  lines.push("            const conv = await K.kvGet(item.conversation_id);");
  lines.push("            if (conv?.reply_target) {");
  lines.push("              turn.reply_target = conv.reply_target;");
  lines.push("            } else {");
  lines.push('              const parts = item.conversation_id.replace("chat:", "").split(":");');
  lines.push('              turn.reply_target = { platform: parts[0], channel: parts.slice(1).join(":"), thread_ts: null };');
  lines.push("            }");
  lines.push("            const result = await runTurn(K, item.conversation_id, [turn]);");
  lines.push('            if (result.action === "sent" || result.action === "discarded") {');
  lines.push("              await K.kvDeleteSafe(item.key);");
  lines.push("            } else {");
  lines.push("              item.attempts = (item.attempts || 0) + 1;");
  lines.push("              if (item.attempts >= 3) {");
  lines.push("                await K.kvDeleteSafe(item.key);");
  lines.push('                await K.karmaRecord({ event: "outbox_dead_lettered", id: item.id });');
  lines.push("              } else {");
  lines.push("                await K.kvWriteSafe(item.key, item);");
  lines.push("              }");
  lines.push("            }");
  lines.push("          } catch (err) {");
  lines.push('            await K.karmaRecord({ event: "outbox_error", id: item.id, error: err.message });');
  lines.push("          }");
  lines.push("        }");
  lines.push("      },");
  lines.push("    },");
  lines.push("  },");
  lines.push("  pulse: { classify: pulseClassify },");
  lines.push("};");
  lines.push("");

  lines.push("export default {");
  lines.push("  async scheduled(event, env, ctx) {");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("    await kernel.runScheduled();");
  lines.push("  },");
  lines.push("");
  lines.push("  async fetch(request, env, ctx) {");
  lines.push("    const url = new URL(request.url);");
  lines.push("");
  lines.push("    const jobMatch = url.pathname.match(/^\\/job-complete\\/([^/]+)$/);");
  lines.push("    if (jobMatch && request.method === 'POST') {");
  lines.push("      const jobId = decodeURIComponent(jobMatch[1]);");
  lines.push("      const rawBody = await request.text();");
  lines.push("      const job = await env.KV.get(`job:${jobId}`, 'json');");
  lines.push("      if (!job) return new Response('Job not found', { status: 404 });");
  lines.push("");
  lines.push("      const providedSecret = request.headers.get('X-Job-Callback-Secret') || '';");
  lines.push("      if (!job.callback_secret || providedSecret !== job.callback_secret) {");
  lines.push("        return new Response('Invalid callback secret', { status: 401 });");
  lines.push("      }");
  lines.push("");
  lines.push("      let payload;");
  lines.push("      try {");
  lines.push("        payload = rawBody ? JSON.parse(rawBody) : {};");
  lines.push("      } catch {");
  lines.push("        return new Response('Invalid JSON', { status: 400 });");
  lines.push("      }");
  lines.push("");
  lines.push("      const exitCode = Number.isFinite(Number(payload?.exit_code)) ? Number(payload.exit_code) : null;");
  lines.push("      if (!Number.isInteger(exitCode)) {");
  lines.push("        return new Response('exit_code is required', { status: 400 });");
  lines.push("      }");
  lines.push("");
  lines.push("      const now = new Date().toISOString();");
  lines.push("      job.status = exitCode === 0 ? 'completed' : 'failed';");
  lines.push("      job.completed_at = now;");
  lines.push("      job.callback_received_at = now;");
  lines.push("      job.exit_code = exitCode;");
  lines.push("");
  lines.push("      const hasOutputArtifact = typeof payload?.output_base64 === 'string' && payload.output_base64.trim();");
  lines.push("      const hasLabArtifact = typeof payload?.lab_result_base64 === 'string' && payload.lab_result_base64.trim();");
  lines.push("      const jobResult = {");
  lines.push("        job_id: jobId,");
  lines.push("        type: job.type,");
  lines.push("        result: null,");
  lines.push("        callback_error: null,");
  lines.push("        lab_result_error: null,");
  lines.push("      };");
  lines.push("");
  lines.push("      if (hasOutputArtifact) {");
  lines.push("        let rawOutput;");
  lines.push("        try {");
  lines.push("          rawOutput = decodeCallbackBase64(payload.output_base64);");
  lines.push("        } catch {");
  lines.push("          jobResult.callback_error = 'invalid_output_base64';");
  lines.push("        }");
  lines.push("        if (rawOutput != null) {");
  lines.push("          const { payload: parsedResult, meta } = parseJobOutput(rawOutput);");
  lines.push("          jobResult.result = parsedResult || { raw_output: rawOutput.slice(0, 5000) };");
  lines.push("          if (meta) jobResult.meta = meta;");
  lines.push("        }");
  lines.push("      } else {");
  lines.push("        jobResult.callback_error = 'callback_missing_output';");
  lines.push("      }");
  lines.push("");
  lines.push("      if (hasLabArtifact) {");
  lines.push("        try {");
  lines.push("          jobResult.lab_result = JSON.parse(decodeCallbackBase64(payload.lab_result_base64));");
  lines.push("        } catch {");
  lines.push("          jobResult.lab_result_error = 'invalid_lab_result_base64';");
  lines.push("        }");
  lines.push("      }");
  lines.push("");
  lines.push("      const resultKey = `job_result:${jobId}`;");
  lines.push("      job.result_key = resultKey;");
  lines.push("      await env.KV.put(resultKey, JSON.stringify(jobResult));");
  lines.push("      await env.KV.put(`job:${jobId}`, JSON.stringify(job));");
  lines.push("");
  lines.push("      const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("      const K = kernel.buildKernelInterface();");
  lines.push("      await K.emitEvent('job_complete', {");
  lines.push("        job_id: jobId,");
  lines.push("        source: { job_id: jobId, via: 'callback' },");
  lines.push("        summary: `Job ${jobId} (${job.type}) ${job.status}`,");
  lines.push("        ref: `job:${jobId}`,");
  lines.push("        result_key: `job_result:${jobId}`,");
  lines.push("        exit_code: exitCode,");
  lines.push("      });");
  lines.push("");
  lines.push("      const defaults = await env.KV.get('config:defaults', 'json');");
  lines.push("      const advanceSeconds = defaults?.jobs?.callback_advance_seconds || 30;");
  lines.push("      await advanceSessionSchedule(env, defaults, advanceSeconds);");
  lines.push("");
  lines.push("      if (ctx?.waitUntil) {");
  lines.push("        ctx.waitUntil((async () => {");
  lines.push("          const wakeKernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("          await wakeKernel.runScheduled();");
  lines.push("        })());");
  lines.push("      }");
  lines.push("");
  lines.push("      return new Response('OK', { status: 202 });");
  lines.push("    }");
  lines.push("");
  lines.push("    if (url.pathname === '/__clear-schedule' && request.method === 'POST') {");
  lines.push("      await env.KV.put('session_schedule', JSON.stringify({");
  lines.push("        next_session_after: new Date(Date.now() - 1000).toISOString(),");
  lines.push("        interval_seconds: 21600,");
  lines.push("      }));");
  lines.push("      return new Response('session_schedule set to past', { status: 200 });");
  lines.push("    }");
  lines.push("");
  lines.push("    if (url.pathname === '/__wake' && request.method === 'POST') {");
  lines.push("      let payload = {};");
  lines.push("      try {");
  lines.push("        payload = await request.json();");
  lines.push("      } catch {");
  lines.push("        return new Response('Invalid JSON', { status: 400 });");
  lines.push("      }");
  lines.push("");
  lines.push("      const actor = typeof payload?.actor === 'string' && payload.actor.trim() ? payload.actor.trim() : 'external';");
  lines.push("      const contextPayload = payload?.context && typeof payload.context === 'object' ? payload.context : {};");
  lines.push("");
  lines.push("      const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("      const K = kernel.buildKernelInterface();");
  lines.push("      await K.emitEvent('wake', {");
  lines.push("        origin: 'external',");
  lines.push("        trigger: { actor, context: contextPayload },");
  lines.push("      });");
  lines.push("");
  lines.push("      const runWake = async () => {");
  lines.push("        const wakeKernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("        await wakeKernel.runScheduled();");
  lines.push("      };");
  lines.push("");
  lines.push("      if (ctx?.waitUntil) ctx.waitUntil(runWake());");
  lines.push("      else await runWake();");
  lines.push("");
  lines.push("      return new Response('wake queued', { status: 202 });");
  lines.push("    }");
  lines.push("");
  lines.push("    const match = url.pathname.match(/^\\/channel\\/(\\w+)$/);");
  lines.push('    if (!match || request.method !== "POST") {');
  lines.push('      return new Response("Not found", { status: 404 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const channel = match[1];");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, mode: 'chat' });");
  lines.push("    const adapterMod = CHANNELS[channel];");
  lines.push('    if (!adapterMod) return new Response(`Unknown channel: ${channel}`, { status: 404 });');
  lines.push("");
  lines.push("    const body = await request.json();");
  lines.push("    const inbound = adapterMod.parseInbound(body);");
  lines.push('    if (!inbound) return new Response("OK", { status: 200 });');
  lines.push("    if (adapterMod.resolveChatKey) inbound.resolvedChatKey = adapterMod.resolveChatKey(inbound);");
  lines.push("    if (inbound._challenge) {");
  lines.push('      return new Response(JSON.stringify({ challenge: inbound._challenge }),');
  lines.push('        { headers: { "Content-Type": "application/json" } });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.msgId) {");
  lines.push("      const dedupKey = `dedup:${inbound.msgId}`;");
  lines.push("      const seen = await kernel.kv.get(dedupKey);");
  lines.push('      if (seen) return new Response("OK", { status: 200 });');
  lines.push('      await kernel.kv.put(dedupKey, "1", { expirationTtl: 60 });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.command) {");
  lines.push("      const K = kernel.buildKernelInterface();");
  lines.push("      await kernel.loadEagerConfig();");
  lines.push("      const result = await handleCommand(K, channel, inbound);");
  lines.push('      if (result) return new Response("OK", { status: 200 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const nonce = Math.random().toString(36).slice(2, 6);");
  lines.push("    const ts = Date.now().toString().padStart(15, '0');");
  lines.push("    const eventKey = `event:${ts}:inbound_message:${nonce}`;");
  lines.push("    const commTurn = ingestInbound(channel, inbound);");
  lines.push("    await env.KV.put(eventKey, JSON.stringify({");
  lines.push('      type: "inbound_message",');
  lines.push("      ...commTurn,");
  lines.push("      idempotency_key: eventKey,");
  lines.push("      timestamp: new Date().toISOString(),");
  lines.push("    }), { expirationTtl: 86400 });");
  lines.push("");
  lines.push('    const schedule = await env.KV.get("session_schedule", "json");');
  lines.push("    if (schedule?.next_session_after) {");
  lines.push("      const now = new Date().toISOString();");
  lines.push("      if (schedule.next_session_after > now) {");
  lines.push('        await env.KV.put("session_schedule", JSON.stringify({');
  lines.push("          ...schedule,");
  lines.push("          next_session_after: now,");
  lines.push("        }));");
  lines.push("      }");
  lines.push("    }");
  lines.push("");
  lines.push('    return new Response("OK", { status: 200 });');
  lines.push("  },");
  lines.push("};");

  return lines.join("\n");
}

// Helper — list all keys with a prefix
async function listKeysWithPrefix(kv, prefix) {
  const keys = [];
  let cursor;
  do {
    const result = await kv.list({ prefix, cursor });
    keys.push(...result.keys.map(k => k.name));
    cursor = result.list_complete ? undefined : result.cursor;
  } while (cursor);
  return keys;
}
