// Governor — Builder
// Reads code from KV and generates the index.js entry point for the runtime worker.
// Also collects all module files needed for the multipart upload.

// Sanitize a KV key into a valid JS identifier
function keyToVarName(key) {
  // tool:kv_query:code → kv_query, provider:llm:code → llm, channel:slack:code → slack
  const parts = key.split(':');
  return parts[parts.length - 2] || parts[0];
}

export function keyToFilePath(key) {
  if (key === 'kernel:source:kernel.js') return 'kernel.js';
  if (key === 'kernel:source:hook-communication.js') return 'hook-communication.js';
  if (key === 'kernel:source:authority-policy.js') return 'authority-policy.js';
  if (!key.endsWith(':code')) return null;
  if (key === 'hook:act:code') return 'act.js';
  if (key === 'hook:session:code') return 'userspace.js';
  if (key === 'hook:reflect:code') return 'reflect.js';
  if (key.startsWith('tool:')) return `tools/${keyToVarName(key)}.js`;
  if (key.startsWith('provider:')) return `providers/${keyToVarName(key)}.js`;
  if (key.startsWith('channel:')) return `channels/${keyToVarName(key)}.js`;
  return null;
}

// Read all mutable code from KV and return { files, metadata }
export async function readCodeFromKV(kv) {
  const files = {};
  const metadata = { tools: [], providers: [], channels: [] };

  // Tools
  const toolKeys = await listKeysWithPrefix(kv, 'tool:');
  for (const key of toolKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`tools/${name}.js`] = code;
      metadata.tools.push(name);
    }
  }

  // Providers
  const providerKeys = await listKeysWithPrefix(kv, 'provider:');
  for (const key of providerKeys) {
    if (!key.endsWith(':code')) continue;
    // Skip last_working snapshots
    if (key.includes(':last_working:')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`providers/${name}.js`] = code;
      metadata.providers.push(name);
    }
  }

  // Channels
  const channelKeys = await listKeysWithPrefix(kv, 'channel:');
  for (const key of channelKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`channels/${name}.js`] = code;
      metadata.channels.push(name);
    }
  }

  // Policy hooks
  const actCode = await kv.get('hook:act:code', 'text');
  if (actCode) files['act.js'] = actCode;

  const sessionCode = await kv.get('hook:session:code', 'text');
  if (sessionCode) files['userspace.js'] = sessionCode;

  const reflectCode = await kv.get('hook:reflect:code', 'text');
  if (reflectCode) files['reflect.js'] = reflectCode;

  // Immutable kernel source (kernel:* — agent cannot modify)
  const kernelCode = await kv.get('kernel:source:kernel.js', 'text');
  if (kernelCode) files['kernel.js'] = kernelCode;

  const commCode = await kv.get('kernel:source:hook-communication.js', 'text');
  if (commCode) files['hook-communication.js'] = commCode;

  const authorityPolicyCode = await kv.get('kernel:source:authority-policy.js', 'text');
  if (authorityPolicyCode) files['authority-policy.js'] = authorityPolicyCode;

  return { files, metadata };
}

// Generate the index.js entry point from module metadata
export function generateIndexJS(metadata) {
  const lines = [];

  lines.push("// Auto-generated by governor — do not edit manually");
  lines.push("import { Kernel } from './kernel.js';");
  lines.push("import { runTurn, ingestInbound, ingestInternal, handleCommand, createOutboxItem, checkOutbox } from './hook-communication.js';");
  lines.push("");

  // Policy hooks
  lines.push("import * as session from './userspace.js';");
  lines.push("import { classify as pulseClassify } from './userspace.js';");
  lines.push("");

  // Channel adapters
  for (const name of metadata.channels) {
    lines.push(`import * as ${name}Adapter from './channels/${name}.js';`);
  }
  lines.push("");

  // Tools
  for (const name of metadata.tools) {
    lines.push(`import * as ${name} from './tools/${name}.js';`);
  }
  lines.push("");

  // Providers
  for (const name of metadata.providers) {
    lines.push(`import * as ${name} from './providers/${name}.js';`);
  }
  lines.push("");

  // Wire modules
  lines.push("const TOOLS = {");
  for (const name of metadata.tools) {
    lines.push(`  ${name},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const PROVIDERS = {");
  for (const name of metadata.providers) {
    lines.push(`  'provider:${name}': ${name},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const CHANNELS = {");
  for (const name of metadata.channels) {
    lines.push(`  ${name}: ${name}Adapter,`);
  }
  lines.push("};");
  lines.push("");

  // EVENT_HANDLERS — immediate event handlers
  lines.push("const EVENT_HANDLERS = {");
  lines.push("  sessionTrigger: async (K, event) => {");
  lines.push('    try {');
  lines.push('      const schedule = await K.kvGet("session_schedule");');
  lines.push('      if (schedule?.next_session_after) {');
  lines.push('        const advanceTo = Date.now() + 30 * 1000;');
  lines.push('        if (new Date(schedule.next_session_after).getTime() > advanceTo) {');
  lines.push('          await K.kvWriteSafe("session_schedule", {');
  lines.push('            ...schedule,');
  lines.push('            next_session_after: new Date(advanceTo).toISOString(),');
  lines.push('          });');
  lines.push('        }');
  lines.push('      }');
  lines.push('    } catch (err) {');
  lines.push('      await K.karmaRecord({ event: "session_wake_error", error: err.message });');
  lines.push('    }');
  lines.push("  },");
  lines.push("};");
  lines.push("");

  // HOOKS — tick (userspace) + deferred processors (run inside lock after tick)
  lines.push("const HOOKS = {");
  lines.push("  tick: session,");
  lines.push("  deferred: {");
  lines.push("    comms: {");
  lines.push("      async run(K, events) {");
  lines.push("        const byConv = {};");
  lines.push("        for (const ev of events) {");
  lines.push('          let turn;');
  lines.push('          if (ev.type === "inbound_message") { turn = ev; if (!turn.idempotency_key) turn.idempotency_key = ev.key; }');
  lines.push('          else { turn = await ingestInternal(K, ev); }');
  lines.push('          if (!turn) {');
  lines.push('            if (ev.key) await K.deleteEvent(ev.key);');
  lines.push('            await K.karmaRecord({ event: "comms_unroutable", event_type: ev.type, event_key: ev.key });');
  lines.push('            continue;');
  lines.push('          }');
  lines.push('          const cid = turn.conversation_id;');
  lines.push('          if (!byConv[cid]) byConv[cid] = [];');
  lines.push('          byConv[cid].push(turn);');
  lines.push("        }");
  lines.push("        for (const [convId, turns] of Object.entries(byConv)) {");
  lines.push("          try {");
  lines.push("            const claimed = [];");
  lines.push("            for (const t of turns) {");
  lines.push("              if (t.idempotency_key) {");
  lines.push("                const ok = await K.claimEvent(t.idempotency_key, await K.getExecutionId());");
  lines.push("                if (ok) claimed.push(t);");
  lines.push("              } else { claimed.push(t); }");
  lines.push("            }");
  lines.push("            if (claimed.length === 0) continue;");
  lines.push("            const result = await runTurn(K, convId, claimed);");
  lines.push("            for (const t of claimed) {");
  lines.push("              if (!t.idempotency_key) continue;");
  lines.push('              if (result.action === "sent" || result.action === "discarded") {');
  lines.push("                await K.deleteEvent(t.idempotency_key);");
  lines.push('              } else if (result.action === "held") {');
  lines.push("                await createOutboxItem(K, convId, t.content, result.reason, result.release_after, [t.idempotency_key]);");
  lines.push("                await K.deleteEvent(t.idempotency_key);");
  lines.push("              } else {");
  lines.push("                await K.releaseEvent(t.idempotency_key);");
  lines.push("              }");
  lines.push("            }");
  lines.push("          } catch (err) {");
  lines.push('            await K.karmaRecord({ event: "comms_error", conversation: convId, error: err.message });');
  lines.push("            for (const t of turns) {");
  lines.push("              if (t.idempotency_key) {");
  lines.push("                try { await K.releaseEvent(t.idempotency_key); } catch {}");
  lines.push("              }");
  lines.push("            }");
  lines.push("          }");
  lines.push("        }");
  lines.push("        const dueItems = await checkOutbox(K);");
  lines.push("        for (const item of dueItems) {");
  lines.push("          try {");
  lines.push("            const turn = {");
  lines.push("              conversation_id: item.conversation_id,");
  lines.push("              reply_target: null,");
  lines.push('              source: "internal",');
  lines.push("              content: item.content,");
  lines.push('              intent: "share",');
  lines.push("              idempotency_key: item.key || null,");
  lines.push("              metadata: { outbox_id: item.id },");
  lines.push("            };");
  lines.push("            const conv = await K.kvGet(item.conversation_id);");
  lines.push("            if (conv?.reply_target) {");
  lines.push("              turn.reply_target = conv.reply_target;");
  lines.push("            } else {");
  lines.push('              const parts = item.conversation_id.replace("chat:", "").split(":");');
  lines.push('              turn.reply_target = { platform: parts[0], channel: parts.slice(1).join(":"), thread_ts: null };');
  lines.push("            }");
  lines.push("            const result = await runTurn(K, item.conversation_id, [turn]);");
  lines.push('            if (result.action === "sent" || result.action === "discarded") {');
  lines.push("              await K.kvDeleteSafe(item.key);");
  lines.push("            } else {");
  lines.push("              item.attempts = (item.attempts || 0) + 1;");
  lines.push("              if (item.attempts >= 3) {");
  lines.push("                await K.kvDeleteSafe(item.key);");
  lines.push('                await K.karmaRecord({ event: "outbox_dead_lettered", id: item.id });');
  lines.push("              } else {");
  lines.push("                await K.kvWriteSafe(item.key, item);");
  lines.push("              }");
  lines.push("            }");
  lines.push("          } catch (err) {");
  lines.push('            await K.karmaRecord({ event: "outbox_error", id: item.id, error: err.message });');
  lines.push("          }");
  lines.push("        }");
  lines.push("      },");
  lines.push("    },");
  lines.push("  },");
  lines.push("  pulse: { classify: pulseClassify },");
  lines.push("};");
  lines.push("");

  lines.push("export default {");
  lines.push("  async scheduled(event, env, ctx) {");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("    await kernel.runScheduled();");
  lines.push("  },");
  lines.push("");
  lines.push("  async fetch(request, env, ctx) {");
  lines.push("    const url = new URL(request.url);");
  lines.push("    const match = url.pathname.match(/^\\/channel\\/(\\w+)$/);");
  lines.push('    if (!match || request.method !== "POST") {');
  lines.push('      return new Response("Not found", { status: 404 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const channel = match[1];");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, mode: 'chat' });");
  lines.push("    const adapterMod = CHANNELS[channel];");
  lines.push('    if (!adapterMod) return new Response(`Unknown channel: ${channel}`, { status: 404 });');
  lines.push("");
  lines.push("    const body = await request.json();");
  lines.push("    const inbound = adapterMod.parseInbound(body);");
  lines.push('    if (!inbound) return new Response("OK", { status: 200 });');
  lines.push("    if (adapterMod.resolveChatKey) inbound.resolvedChatKey = adapterMod.resolveChatKey(inbound);");
  lines.push("    if (inbound._challenge) {");
  lines.push('      return new Response(JSON.stringify({ challenge: inbound._challenge }),');
  lines.push('        { headers: { "Content-Type": "application/json" } });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.msgId) {");
  lines.push("      const dedupKey = `dedup:${inbound.msgId}`;");
  lines.push("      const seen = await kernel.kv.get(dedupKey);");
  lines.push('      if (seen) return new Response("OK", { status: 200 });');
  lines.push('      await kernel.kv.put(dedupKey, "1", { expirationTtl: 60 });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.command) {");
  lines.push("      const K = kernel.buildKernelInterface();");
  lines.push("      await kernel.loadEagerConfig();");
  lines.push("      const result = await handleCommand(K, channel, inbound);");
  lines.push('      if (result) return new Response("OK", { status: 200 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const nonce = Math.random().toString(36).slice(2, 6);");
  lines.push("    const ts = Date.now().toString().padStart(15, '0');");
  lines.push("    const eventKey = `event:${ts}:inbound_message:${nonce}`;");
  lines.push("    const commTurn = ingestInbound(channel, inbound);");
  lines.push("    await env.KV.put(eventKey, JSON.stringify({");
  lines.push('      type: "inbound_message",');
  lines.push("      ...commTurn,");
  lines.push("      idempotency_key: eventKey,");
  lines.push("      timestamp: new Date().toISOString(),");
  lines.push("    }), { expirationTtl: 86400 });");
  lines.push("");
  lines.push('    const schedule = await env.KV.get("session_schedule", "json");');
  lines.push("    if (schedule?.next_session_after) {");
  lines.push("      const now = new Date().toISOString();");
  lines.push("      if (schedule.next_session_after > now) {");
  lines.push('        await env.KV.put("session_schedule", JSON.stringify({');
  lines.push("          ...schedule,");
  lines.push("          next_session_after: now,");
  lines.push("        }));");
  lines.push("      }");
  lines.push("    }");
  lines.push("");
  lines.push('    return new Response("OK", { status: 200 });');
  lines.push("  },");
  lines.push("};");

  return lines.join("\n");
}

// Helper — list all keys with a prefix
async function listKeysWithPrefix(kv, prefix) {
  const keys = [];
  let cursor;
  do {
    const result = await kv.list({ prefix, cursor });
    keys.push(...result.keys.map(k => k.name));
    cursor = result.list_complete ? undefined : result.cursor;
  } while (cursor);
  return keys;
}
