// Governor — Builder
// Reads code from KV and generates the index.js entry point for the runtime worker.
// Also collects all module files needed for the multipart upload.

// Sanitize a KV key into a valid JS identifier
function keyToVarName(key) {
  // tool:kv_query:code → kv_query, provider:llm:code → llm, channel:slack:code → slack
  const parts = key.split(':');
  return parts[parts.length - 2] || parts[0];
}

export function keyToFilePath(key) {
  if (!key.endsWith(':code')) return null;
  if (key === 'hook:act:code') return 'act.js';
  if (key === 'hook:reflect:code') return 'reflect.js';
  if (key === 'hook:session:code') return 'userspace.js';
  if (key.startsWith('tool:')) return `tools/${keyToVarName(key)}.js`;
  if (key.startsWith('provider:')) return `providers/${keyToVarName(key)}.js`;
  if (key.startsWith('channel:')) return `channels/${keyToVarName(key)}.js`;
  return null;
}

// Read all mutable code from KV and return { files, metadata }
export async function readCodeFromKV(kv) {
  const files = {};
  const metadata = { tools: [], providers: [], channels: [] };

  // Tools
  const toolKeys = await listKeysWithPrefix(kv, 'tool:');
  for (const key of toolKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`tools/${name}.js`] = code;
      metadata.tools.push(name);
    }
  }

  // Providers
  const providerKeys = await listKeysWithPrefix(kv, 'provider:');
  for (const key of providerKeys) {
    if (!key.endsWith(':code')) continue;
    // Skip last_working snapshots
    if (key.includes(':last_working:')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`providers/${name}.js`] = code;
      metadata.providers.push(name);
    }
  }

  // Channels
  const channelKeys = await listKeysWithPrefix(kv, 'channel:');
  for (const key of channelKeys) {
    if (!key.endsWith(':code')) continue;
    const name = keyToVarName(key);
    const code = await kv.get(key, 'text');
    if (code) {
      files[`channels/${name}.js`] = code;
      metadata.channels.push(name);
    }
  }

  // Policy hooks (act.js, reflect.js)
  const actCode = await kv.get('hook:act:code', 'text');
  if (actCode) files['act.js'] = actCode;

  const reflectCode = await kv.get('hook:reflect:code', 'text');
  if (reflectCode) files['reflect.js'] = reflectCode;

  const sessionCode = await kv.get('hook:session:code', 'text');
  if (sessionCode) files['userspace.js'] = sessionCode;

  // Immutable kernel source (kernel:* — agent cannot modify)
  const kernelCode = await kv.get('kernel:source:kernel.js', 'text');
  if (kernelCode) files['kernel.js'] = kernelCode;

  const commCode = await kv.get('kernel:source:hook-communication.js', 'text');
  if (commCode) files['hook-communication.js'] = commCode;

  return { files, metadata };
}

// Generate the index.js entry point from module metadata
export function generateIndexJS(metadata) {
  const lines = [];

  lines.push("// Auto-generated by governor — do not edit manually");
  lines.push("import { Kernel } from './kernel.js';");
  lines.push("import { runTurn, ingestInbound, ingestInternal, handleCommand, createOutboxItem, checkOutbox } from './hook-communication.js';");
  lines.push("");

  // Policy hooks
  lines.push("import * as session from './userspace.js';");
  lines.push("");

  // Channel adapters
  for (const name of metadata.channels) {
    lines.push(`import * as ${name}Adapter from './channels/${name}.js';`);
  }
  lines.push("");

  // Tools
  for (const name of metadata.tools) {
    lines.push(`import * as ${name} from './tools/${name}.js';`);
  }
  lines.push("");

  // Providers
  for (const name of metadata.providers) {
    lines.push(`import * as ${name} from './providers/${name}.js';`);
  }
  lines.push("");

  // Wire modules
  lines.push("const TOOLS = {");
  for (const name of metadata.tools) {
    lines.push(`  ${name},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const PROVIDERS = {");
  for (const name of metadata.providers) {
    lines.push(`  'provider:${name}': ${name},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const CHANNELS = {");
  for (const name of metadata.channels) {
    lines.push(`  ${name}: ${name}Adapter,`);
  }
  lines.push("};");
  lines.push("");

  lines.push("const HOOKS = { tick: session };");
  lines.push("");

  // Entry points — governor generates same structure as hand-written index.js
  // EVENT_HANDLERS and full scheduled/fetch logic are included inline
  lines.push("const EVENT_HANDLERS = {");
  lines.push("  communicationDelivery: async (K, event) => {");
  lines.push("    if (!EVENT_HANDLERS._pendingComms) EVENT_HANDLERS._pendingComms = [];");
  lines.push("    EVENT_HANDLERS._pendingComms.push(event);");
  lines.push("  },");
  lines.push("  sessionTrigger: async (K, event) => {");
  lines.push('    try {');
  lines.push('      const schedule = await K.kvGet("session_schedule");');
  lines.push('      if (schedule?.next_session_after) {');
  lines.push('        const advanceTo = Date.now() + 30 * 1000;');
  lines.push('        if (new Date(schedule.next_session_after).getTime() > advanceTo) {');
  lines.push('          await K.kvWriteSafe("session_schedule", {');
  lines.push('            ...schedule,');
  lines.push('            next_session_after: new Date(advanceTo).toISOString(),');
  lines.push('          });');
  lines.push('        }');
  lines.push('      }');
  lines.push('    } catch (err) {');
  lines.push('      await K.karmaRecord({ event: "session_wake_error", error: err.message });');
  lines.push('    }');
  lines.push("  },");
  lines.push("};");
  lines.push("");

  lines.push("export default {");
  lines.push("  async scheduled(event, env, ctx) {");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, EVENT_HANDLERS });");
  lines.push("    await kernel.runScheduled();");
  lines.push("  },");
  lines.push("");
  lines.push("  async fetch(request, env, ctx) {");
  lines.push("    const url = new URL(request.url);");
  lines.push("    const match = url.pathname.match(/^\\/channel\\/(\\w+)$/);");
  lines.push('    if (!match || request.method !== "POST") {');
  lines.push('      return new Response("Not found", { status: 404 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const channel = match[1];");
  lines.push("    const kernel = new Kernel(env, { ctx, TOOLS, HOOKS, PROVIDERS, CHANNELS, mode: 'chat' });");
  lines.push("    const adapterMod = CHANNELS[channel];");
  lines.push('    if (!adapterMod) return new Response(`Unknown channel: ${channel}`, { status: 404 });');
  lines.push("");
  lines.push("    const body = await request.json();");
  lines.push("    const inbound = adapterMod.parseInbound(body);");
  lines.push('    if (!inbound) return new Response("OK", { status: 200 });');
  lines.push("    if (adapterMod.resolveChatKey) inbound.resolvedChatKey = adapterMod.resolveChatKey(inbound);");
  lines.push("    if (inbound._challenge) {");
  lines.push('      return new Response(JSON.stringify({ challenge: inbound._challenge }),');
  lines.push('        { headers: { "Content-Type": "application/json" } });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.msgId) {");
  lines.push("      const dedupKey = `dedup:${inbound.msgId}`;");
  lines.push("      const seen = await kernel.kv.get(dedupKey);");
  lines.push('      if (seen) return new Response("OK", { status: 200 });');
  lines.push('      await kernel.kv.put(dedupKey, "1", { expirationTtl: 60 });');
  lines.push("    }");
  lines.push("");
  lines.push("    if (inbound.command) {");
  lines.push("      const K = kernel.buildKernelInterface();");
  lines.push("      await kernel.loadEagerConfig();");
  lines.push("      const result = await handleCommand(K, channel, inbound);");
  lines.push('      if (result) return new Response("OK", { status: 200 });');
  lines.push("    }");
  lines.push("");
  lines.push("    const nonce = Math.random().toString(36).slice(2, 6);");
  lines.push("    const ts = Date.now().toString().padStart(15, '0');");
  lines.push("    const eventKey = `event:${ts}:inbound_message:${nonce}`;");
  lines.push("    const commTurn = ingestInbound(channel, inbound);");
  lines.push("    await env.KV.put(eventKey, JSON.stringify({");
  lines.push('      type: "inbound_message",');
  lines.push("      ...commTurn,");
  lines.push("      timestamp: new Date().toISOString(),");
  lines.push("    }), { expirationTtl: 86400 });");
  lines.push("");
  lines.push('    const schedule = await env.KV.get("session_schedule", "json");');
  lines.push("    if (schedule?.next_session_after) {");
  lines.push("      const now = new Date().toISOString();");
  lines.push("      if (schedule.next_session_after > now) {");
  lines.push('        await env.KV.put("session_schedule", JSON.stringify({');
  lines.push("          ...schedule,");
  lines.push("          next_session_after: now,");
  lines.push("        }));");
  lines.push("      }");
  lines.push("    }");
  lines.push("");
  lines.push('    return new Response("OK", { status: 200 });');
  lines.push("  },");
  lines.push("};");

  return lines.join("\n");
}

// Helper — list all keys with a prefix
async function listKeysWithPrefix(kv, prefix) {
  const keys = [];
  let cursor;
  do {
    const result = await kv.list({ prefix, cursor });
    keys.push(...result.keys.map(k => k.name));
    cursor = result.list_complete ? undefined : result.cursor;
  } while (cursor);
  return keys;
}
